version: '3'

services:

  drupal:
    image: drupal:8.8.2
    restart: always
    ports:
      - "8003:80"
    volumes:
    - web-modules:/var/www/html/modules
    - web-profiles:/var/www/html/profiles
    - web-sites:/var/www/html/sites
    - web-themes:/var/www/html/themes
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    restart: always
    ports:
      - "8004:5432"
    environment:
      POSTGRES_DB: drupaldb
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example@123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  web-modules:
  web-profiles:
  web-themes:
  web-sites: